name: farmers_market
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  rxdart: ^0.28.0
  provider: ^6.1.2
  fluttertoast: ^8.2.10
  uuid: ^4.5.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

  date_format: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
